force-app/main/default/objects/AccountApproval__c/AccountApproval__c.object-meta.xml
<CustomObject>
    <label>AccountApproval</label>
    <nameField>
        <label>AccountApproval Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AccountApprovals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountApproval__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>AccountApprovals</relationshipLabel>
    <relationshipName>AccountApprovals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountApproval__c/fields/Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>Approver_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AccountApprovals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountApprovalController.cls
global class AccountApprovalController {
    @AuraEnabled
    public static boolean saveAccountApprovar(String title,String accountId,String approvalId){
        AccountApproval__c accApproval = new AccountApproval__c();
        accApproval.Title__c =title;
        accApproval.Account_Name__c = accountId;
        accApproval.Approver_Name__c = approvalId;
        
        try{
            insert accApproval;
            return true;
        }catch(Exception e){
            System.debug(e.getMessage());
            return false;
        }
    }
}